name: test

on: [push, pull_request]

jobs:
  test:
    name: Test django-advanced-password-validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - { "djangoVersion": "4.1.2", "pythonVersion": "3.10" }
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python 🐍
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.versions.pythonVersion }}
      - name: Install dependencies 📦
        run: python -m pip install -r requirements_test.txt && python -m pip install -e .
      - name: Install Django ${{ matrix.versions.djangoVersion }} 📦
        run: python -m pip install Django==${{ matrix.versions.djangoVersion }}
      - name: Check types, syntax and duckstrings 🦆
        run: |
          mypy --exclude=setup.py .
          flake8 .
          interrogate --quiet --fail-under=95 .
      - name: Test Django ${{ matrix.versions.djangoVersion }} with coverage 🧪
        run: coverage run --source=django_saml2_auth -m pytest . && coverage lcov -o coverage.lcov
      - name: Submit coverage report to Coveralls 📈
        if: ${{ success() }}
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov

